check binary exists before programming the promicro

diff --git a/bin/prog-pro-micro b/bin/prog-pro-micro
--- a/bin/prog-pro-micro
+++ b/bin/prog-pro-micro
@@ -5,6 +5,14 @@ set -e
 dev='/dev/ttyACM0'
 
 #
+# check binary file exists
+#
+if [ ! -f $1 ]; then
+  echo -e "failed!\nerror: invalid file $1"
+  exit 1
+fi
+
+#
 # determine flash/eeprom binary
 #
 echo -n "checking hex file..."
